# This is a basic workflow to help you get started with Actions

name: 'Assignment 2: Deploy infrastructure - Dev workspace'

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - 'dev' 
    paths:
      - 'Course materials/assignment2/**'

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  WORKING_DIR: ./Course materials/assignment2
  
jobs:
    dev:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Terraform init
          run: terraform init
          working-directory: ${{ env.WORKING_DIR }}
          
        - name: Terraform workspace select or create dev
          run: terraform workspace select dev || terraform workspace new dev
          working-directory: ${{ env.WORKING_DIR }}
        
        - name: Terraform plan
          run: terraform plan
          working-directory: ${{ env.WORKING_DIR }}
        
        - name: Terraform apply dev
          run: terraform apply -auto-approve
          working-directory: ${{ env.WORKING_DIR }}
